name: work

on:
  push:
    branches: [ L2 ]
  pull_request:
    branches: [ L2 ]
  workflow_dispatch:

jobs:

  build_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          g++ main.cpp -o app_${RUNNER_OS}_ver.${GITHUB_RUN_NUMBER}
          ./app_${RUNNER_OS}_ver.${GITHUB_RUN_NUMBER}
      - name: Upload a build artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: my_app
          path: app_**
          # удаление созданных артефактов через 1 день
          retention-days: 1
    
  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          g++ main.cpp -o app_${RUNNER_OS}_ver.${GITHUB_RUN_NUMBER}
          ./app_${RUNNER_OS}_ver.${GITHUB_RUN_NUMBER}
      - name: Upload a build artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: my_app
          path: app_**
          # удаление созданных артефактов через 1 день
          retention-days: 1
 
  build_win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: cl /EHsc main.cpp
      - name: Upload a build artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: my_app
          path: main.exe
          retention-days: 1
