name: work 08.02.2022

on:
  push:
    branches: [ L3 ]
  pull_request:
    branches: [ L3 ]
  workflow_dispatch:

jobs: 
  build_macos_and_ubuntu:
    #несколько вариантов для запуска (выберется тот, где есть ольше мощностей)
    #runs-on: [ macos-latest, ubuntu-latest ]
    
    #выбор всех систем с помощью следующей стратегии
    runs-on: ${{matrix.os}}
    #конструкция для перебирания всех значений матрицы
    strategy:
      #создание матрицы
      matrix:
        #создание объекта os в матрице
        os: [macos-latest, ubuntu-latest]
        #параметры для запуска gcc компилятора (уровни оптимизации
        gcc_o: ["-O0", "-O3"]
        #параметры для исключения из матрицы (не будет билдиться для macos с максимальной оптимизацией)
        exclude:
          - os: macos-latest
            gcc_o: "-O3"
          
    #переменная app_name на уровне job-а
    env:
      app_name: app-${{ matrix.os }}${{ matrix.gcc_o }}_ver:${{ github.run_number }}
    steps:
      #выкачивает ветку с файлами (без этого не запустить g++ main.cpp -o app_$ImageOS)
      - uses: actions/checkout@v2
      - name: build
        #компиляция и выполнение приложения с названием из переменной среды
        run: |
          g++ main.cpp ${{ matrix.gcc_o }} -o ${{ env.app_name }}
          ./${{ env.app_name }}
       #создание артефактов
      - name: Upload a build artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          #имя папки для артефактов
          name: my_app
          #добавление артефакта по имени(регулярка)
          path: ${{ env.app_name }}
          # удаление созданных артефактов через 1 день
          retention-days: 1
 
  build_windows:
    runs-on: windows-latest
    steps:
      #выкачивает ветку с файлами (без этого не запустить g++ main.cpp -o app_$ImageOS)
      - uses: actions/checkout@v2
      #добавление компилятора для windows
      - uses: ilammy/msvc-dev-cmd@v1
      - name: build
        run: cl /EHsc main.cpp
      #создание артефактов
      - name: Upload a build artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          #имя папки для артефактов
          name: my_app
          #добавление артефакта по имени
          path: main.exe
          # удаление созданных артефактов через 1 день
          retention-days: 1
